.PHONY: all
MAKEFLAGS += --silent

all: install

# install depedencies
install:
	sudo npm i -g typescript-language-server typescript graphql-language-service-cli sql-formatter@4.0.2 @fsouza/prettierd
